name: outwiker
version: '{version}'
summary: Cross-platform software for keeping your notes in a tree
description: |
    OutWiker is a cross-platform software for keeping your notes in a tree.
    Similar programs call "outliner", "tree-like editor" or personal wiki.
    Main difference OutWiker from other programs is a keeping notes as folders on disk.
    A notes can to have attached files. OutWiker can contain pages of different types,
    currently supports three types of pages: plain text, HTML pages and wiki pages.

grade: stable # must be 'stable' to release into candidate/stable channels
confinement: strict # use 'strict' once you have the right plugs and slots
icon: usr/share/icons/outwiker.svg
base: core20

apps:
    outwiker:
        # command: bin/snapcraft-preload $SNAP/usr/bin/outwiker
        # command: bin/snapcraft-preload usr/bin/outwiker
        command: usr/bin/outwiker
        plugs:
            - x11
            - unity7
            - wayland
            - pulseaudio
            - home
            - gsettings
            - network
            - network-bind
            - cups-control
            - desktop
            - desktop-legacy
            - removable-media
            - upower-observe
            - mount-observe
        extensions:
            - gnome-3-38
        desktop: usr/share/applications/outwiker.desktop
        #environment:
        #    LD_LIBRARY_PATH: $SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/webkit2gtk-4.0/:$SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/pulseaudio:$SNAP/lib/python3/site-packages/hunspell:$LD_LIBRARY_PATH
            #PYTHONPATH: $SNAP/lib/python3.8/site-packages/

parts:
    outwiker:
        #after:
        #    - snapcraft-preload
        plugin: nil
        #plugin: python
        source: .
        build-packages:
            - libhunspell-dev
            - wget
            - libwebkit2gtk-4.0-dev
            - freeglut3-dev
            - libgl1-mesa-dev
            - libglu1-mesa-dev
            - libgstreamer-plugins-base1.0-dev
            - libjpeg-dev
            - libnotify-dev
            - libpng-dev
            - libsdl2-dev
            - libsm-dev
            - libtiff-dev
            - libxtst-dev
            - g++-10
            - gcc-10
            - build-essential
        stage-packages:
            - python3
            - python3-venv
            - python3-dev
            - python3-distutils
            - python3-setuptools
            - python3-pip
            - libglu1-mesa
            - libsdl2-2.0-0
            - libsndio7.0
            - libxss1
            - freeglut3
            - ibus-gtk3
            - zlib1g
            - libsm6
            - libpulse0
            - libhunspell-1.7-0
            - libsdl-gfx1.2-5
            - libgstreamer1.0-0
            - libslang2
        #python-packages:
        #    - -f https://extras.wxpython.org/wxPython4/extras/linux/gtk3/ubuntu-20.04 wxPython==4.2.1
        #    - Pillow==9.5.0
        #    - cyhunspell==2.0.2
        #    - idna==2.10
        #    - pyparsing==3.0.9
        #    - rcssmin==1.1.1
        override-build: |
            python3 -m venv $SNAPCRAFT_PART_INSTALL/venv
            . $SNAPCRAFT_PART_INSTALL/venv/bin/activate
            #mkdir $SNAPCRAFT_PART_INSTALL/python-packages
            python -m pip install -f https://extras.wxpython.org/wxPython4/extras/linux/gtk3/ubuntu-20.04 wxPython==4.2.1
            python -m pip install Pillow==9.5.0 idna==2.10 pyparsing==3.0.9 rcssmin==1.1.1
            #snapcraftctl build
            cd $SNAPCRAFT_PART_SRC/depends/cacheman
            python setup.py clean
            python setup.py install
            #g++ --version
            #gcc --version
            cd $SNAPCRAFT_PART_SRC/depends/cyhunspell
            python setup.py clean
            python setup.py install
            cp -r $SNAPCRAFT_PART_SRC/usr $SNAPCRAFT_PART_INSTALL
            chmod +x $SNAPCRAFT_PART_INSTALL/usr/bin/outwiker

    #snapcraft-preload:
    #    source: https://github.com/sergiusens/snapcraft-preload.git
    #    plugin: cmake
    #    build-packages:
    #      - gcc-multilib
    #      - g++-multilib
    #    stage-packages:
    #      - lib32stdc++6
