name: outwiker
version: '{version}'
summary: Cross-platform software for keeping your notes in a tree
description: |
    OutWiker is a cross-platform software for keeping your notes in a tree.
    Similar programs call "outliner", "tree-like editor" or personal wiki.
    Main difference OutWiker from other programs is a keeping notes as folders on disk.
    A notes can to have attached files. OutWiker can contain pages of different types,
    currently supports three types of pages: plain text, HTML pages and wiki pages.

grade: stable # must be 'stable' to release into candidate/stable channels
confinement: strict # use 'strict' once you have the right plugs and slots
icon: usr/share/icons/outwiker.svg
base: core18
package-repositories:
    - type: apt
      ppa: deadsnakes/ppa

apps:
    outwiker:
        command: bin/snapcraft-preload $SNAP/usr/bin/outwiker
        plugs:
            - x11
            - unity7
            - wayland
            - pulseaudio
            - home
            - gsettings
            - network
            - network-bind
            - cups-control
            - desktop
            - desktop-legacy
            - removable-media
            - upower-observe
            - mount-observe
        extensions:
            - gnome-3-34
        desktop: usr/share/applications/outwiker.desktop
        # environment:
        #     LD_LIBRARY_PATH: $SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/webkit2gtk-4.0/:$SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/pulseaudio:$LD_LIBRARY_PATH

parts:
    outwiker:
        after:
            #- python
            - snapcraft-preload
            # - webkitgtk
        plugin: nil
        #plugin: python
        #python-version: python3
        source: .
        build-packages:
            - libhunspell-dev
            - python3.9-dev
            - python3.9-distutils
            - wget
            #- python3-dev
            # - libwebkit2gtk-4.0-dev
            # - python3-dev
            # - libssl-dev
            # - build-essential
            # - libjpeg-dev
            # - libtiff-dev
            # - libsdl2-dev
            # - libgstreamer-plugins-base1.0-dev
            # - libnotify-dev
            # - freeglut3-dev
            # - libsm-dev
            # - libgtk-3-dev
        stage-packages:
            #- python3
            - python3.9
            - python3.9-venv
            - libglu1-mesa
            - libsdl2-2.0-0
            - libsndio6.1
            - libxss1
            - freeglut3
            - ibus-gtk3
            - zlib1g
            - libsm6
            - libpulse0
            - libhunspell-1.6-0
            # - libwebkit2gtk-4.0-37
            - libsdl-gfx1.2-5
            - libgstreamer1.0-0
            - libslang2
        #python-packages:
        #    - https://extras.wxpython.org/wxPython4/extras/linux/gtk3/ubuntu-18.04/wxPython-4.1.1-cp39-cp39-linux_x86_64.whl
        #    - Pillow==8.2.0
        #    - cyhunspell==2.0.1
        #    - idna==2.10
        #    - pyparsing==3.0.7
        override-build: |
            #snapcraftctl build
            wget -O $SNAPCRAFT_PART_INSTALL/usr/bin/get-pip.py https://bootstrap.pypa.io/get-pip.py
            python3.9 $SNAPCRAFT_PART_INSTALL/usr/bin/get-pip.py
            python3.9 -m pip install https://extras.wxpython.org/wxPython4/extras/linux/gtk3/ubuntu-18.04/wxPython-4.1.1-cp39-cp39-linux_x86_64.whl Pillow==9.1.1 cyhunspell==2.0.2 idna==2.10 pyparsing==3.0.9
            cp -r $SNAPCRAFT_PART_SRC/usr $SNAPCRAFT_PART_INSTALL
            chmod +x $SNAPCRAFT_PART_INSTALL/usr/bin/outwiker

    snapcraft-preload:
        source: https://github.com/sergiusens/snapcraft-preload.git
        plugin: cmake
        build-packages:
          - gcc-multilib
          - g++-multilib
        stage-packages:
          - lib32stdc++6

    #python:
    #    plugin: autotools
    #    source: https://www.python.org/ftp/python/3.9.8/Python-3.9.8.tgz
    #    configflags:
    #      - --enable-optimizations
    #    build-packages:
    #      - build-essential
    #      - gdb 
    #      - lcov
    #      - pkg-config
    #      - libbz2-dev 
    #      - libffi-dev 
    #      - libgdbm-dev 
    #      - libgdbm-compat-dev 
    #      - liblzma-dev
    #      - libncurses5-dev
    #      - libreadline6-dev
    #      - libsqlite3-dev
    #      - libssl-dev
    #      - lzma
    #      - lzma-dev 
    #      - tk-dev 
    #      - uuid-dev 
    #      - zlib1g-dev
    #    override-stage: |
    #      snapcraftctl stage
    #      [ ! -d "${SNAPCRAFT_STAGE}/bin" ] && mkdir ${SNAPCRAFT_STAGE}/bin
    #      ln -s ../usr/local/bin/python3.9 "${SNAPCRAFT_STAGE}/bin/python3.9"
    #      ln -s ../usr/local/bin/python3.9 "${SNAPCRAFT_STAGE}/usr/bin/python3"
    #    stage-packages:
    #      - libfontconfig1
    #      - libfreetype6
    #      - libgdbm-compat4
    #      - libgdbm6
    #      - libpng16-16
    #      - libtcl8.6
    #      - libtk8.6
    #      - libx11-6
    #      - libxau6
    #      - libxcb1
    #      - libxdmcp6
    #      - libxext6
    #      - libxft2
    #      - libxrender1
    #      - libxss1

    # webkitgtk:
    #     plugin: cmake
    #     configflags:
    #         - -DCMAKE_C_COMPILER=clang
    #         - -DCMAKE_CXX_COMPILER=clang++
    #         - -DLIBEXEC_INSTALL_DIR=/usr/libexec/webkit2gtk-4.0
    #         - -DCMAKE_INSTALL_PREFIX=/
    #         - -DCMAKE_BUILD_TYPE=Release
    #         - -DPORT=GTK
    #         # - -DENABLE_WEB_CRYPTO=0
    #         # - -DUSE_OPENJPEG=0
    #         # - -DUSE_WOFF2=0
    #         # - -DUSE_GSTREAMER_GL=0
    #         # - -DENABLE_OPENGL=OFF
    #         # - -DENABLE_ACCELERATED_2D_CANVAS=ON
    #         # - -DENABLE_CSS3_TEXT=ON
    #         # - -DENABLE_CSS_COMPOSITING=ON
    #         # - -DENABLE_CSS_IMAGE_ORIENTATION=ON
    #         - -DENABLE_MINIBROWSER=ON
    #         - -DENABLE_MEDIA_SOURCE=0
    #         - -DUSE_WPE_RENDERER=0
    #         - -DENABLE_BUBBLEWRAP_SANDBOX=0
    #     # source: https://www.webkitgtk.org/releases/webkitgtk-2.28.2.tar.xz
    #     # source: https://www.webkitgtk.org/releases/webkitgtk-2.25.92.tar.xz
    #     # source: https://www.webkitgtk.org/releases/webkitgtk-2.24.1.tar.xz
    #     source: https://jenyay.net/uploads/Outwiker/Dev/webkitgtk-2.28.1.tar.xz
    #     build-packages:
    #         - clang
    #         - ruby
    #         - libgcrypt20-dev
    #         - libwebp-dev
    #         - libxslt1-dev
    #         - libsecret-1-dev
    #         - libtasn1-6-dev
    #         - libenchant-dev
    #         - libhyphen-dev
    #         - libjpeg-dev
    #         - libsoup2.4-dev
    #         - libxkbcommon-dev
    #         - libnghttp2-14
    #         - libpixman-1-dev
    #         - libsqlite3-dev
    #         - libgl1-mesa-dev
    #         - freeglut3-dev 
    #         - libgirepository1.0-dev
    #         - libgtk-3-dev
    #         - libgtk2.0-dev
    #         - libnotify-dev
    #         - libgstreamer1.0-dev
    #         - libgstreamer-plugins-base1.0-dev
    #         - libopenjp2-7-dev
    #         - libwoff-dev
    #         - ninja-build
    #     stage-packages:
    #         - libc6
    #         - libstdc++6
    #         - libgl1
    #         - libgles2
    #         - geoclue-2.0
    #         - gperf
    #         - gobject-introspection
    #         - gettext
    #         - libgtk2.0-0
    #         - libopenjp2-7
    #         - libxt6
