name: outwiker
version: '{version}'
summary: Cross-platform software for keeping your notes in a tree
description: |
  OutWiker is a cross-platform software for keeping your notes in a tree.
  Similar programs call "outliner", "tree-like editor" or personal wiki.
  Main difference OutWiker from other programs is a keeping notes as folders on disk.
  A notes can to have attached files. OutWiker can contain pages of different types,
  currently supports three types of pages: plain text, HTML pages and wiki pages.

grade: stable # must be 'stable' to release into candidate/stable channels
confinement: strict # use 'strict' once you have the right plugs and slots
icon: usr/share/icons/outwiker.svg
base: core22

apps:
  outwiker:
    command: usr/bin/outwiker
    plugs:
      - x11
      - unity7
      - wayland
      - pulseaudio
      - home
      - gsettings
      - network
      - network-bind
      - cups-control
      - desktop
      - desktop-legacy
      - removable-media
      - upower-observe
      - mount-observe
      - locale-control
    extensions:
      - gnome
    desktop: usr/share/applications/outwiker.desktop
    environment:
      LD_LIBRARY_PATH: $SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/webkit2gtk-4.0/:$SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/pulseaudio:$SNAP/pylib/cyhunspell-2.0.3.post1-py3.10-linux-x86_64.egg/hunspell:$SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET:$SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/libgtk-3-0:$LD_LIBRARY_PATH
      PYTHONPATH: $SNAP/pylib
      PATH: $SNAP/usr/bin:$SNAP/pylib:$PATH

layout:
  /usr/lib/locale:
    bind: $SNAP/usr/lib/locale
  /usr/lib/$SNAPCRAFT_ARCH_TRIPLET/webkit2gtk-4.0:
    bind: $SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/webkit2gtk-4.0
  /usr/share/xml/iso-codes:
    bind: $SNAP/usr/share/xml/iso-codes

plugs:
  gtk-3-themes:
    default-provider: gtk-common-themes
    interface: content
    target: $SNAP/usr/share/themes
  icon-themes:
    default-provider: gtk-common-themes
    interface: content
    target: $SNAP/usr/share/icons
  sound-themes:
    default-provider: gtk-common-themes
    interface: content
    target: $SNAP/usr/share/sounds

parts:
  outwiker:
    plugin: nil
    source: .
    build-packages:
      - python3.10-dev
      - python3-pip
      - libhunspell-dev
      - libwebkit2gtk-4.0-dev
      - freeglut3-dev
      - libgstreamer-plugins-base1.0-dev
      - libjpeg-dev
      - libnotify-dev
      - libpng-dev
      - libsdl2-dev
      - libsm-dev
      - libtiff-dev
      - libxtst-dev
      - g++-10
      - gcc-10
      - build-essential
      - autoconf
      - automake
      - libtool
    stage-packages:
      - python3.10
      - python3-distutils
      - libsdl2-2.0-0
      - libxss1
      - freeglut3
      - ibus-gtk3
      - libpulse0
      - libhunspell-1.7-0
      - libegl1
      - libenchant-2-2
      - libjavascriptcoregtk-4.0-18
      - libwebkit2gtk-4.0-37
      - libwebpdemux2
      - libgnutls30
      - xdg-user-dirs
      - libcanberra-gtk3-module
    override-build: |
      pip3 install -t $SNAPCRAFT_PART_INSTALL/pylib -f https://extras.wxpython.org/wxPython4/extras/linux/gtk3/ubuntu-22.04 wxPython==4.2.2
      pip3 install -t $SNAPCRAFT_PART_INSTALL/pylib Pillow==10.2.0 idna==2.10 pyparsing==3.0.9 rcssmin==1.1.1 wheel setuptools
      cd $SNAPCRAFT_PART_SRC/depends/cacheman
      python3 setup.py bdist
      python3 setup.py bdist_wheel
      pip3 install -t $SNAPCRAFT_PART_INSTALL/pylib dist/CacheMan-2.1.0.post1-py2.py3-none-any.whl
      cd $SNAPCRAFT_PART_SRC/depends/cyhunspell
      python3 setup.py bdist
      python3 setup.py bdist_wheel
      pip3 install -t $SNAPCRAFT_PART_INSTALL/pylib dist/cyhunspell-2.0.3.post1-cp310-cp310-linux_x86_64.whl
      cp -r $SNAPCRAFT_PART_SRC/usr $SNAPCRAFT_PART_INSTALL
      chmod +x $SNAPCRAFT_PART_INSTALL/usr/bin/outwiker
