name: outwiker
version: '{version}'
summary: Cross-platform software for keeping your notes in a tree
description: |
    OutWiker is a cross-platform software for keeping your notes in a tree.
    Similar programs call "outliner", "tree-like editor" or personal wiki.
    Main difference OutWiker from other programs is a keeping notes as folders on disk.
    A notes can to have attached files. OutWiker can contain pages of different types,
    currently supports three types of pages: plain text, HTML pages and wiki pages.

grade: devel # must be 'stable' to release into candidate/stable channels
confinement: strict # use 'strict' once you have the right plugs and slots
icon: usr/share/icons/outwiker.svg

apps:
    outwiker:
        command: desktop-launch snapcraft-preload $SNAP/usr/bin/outwiker
        plugs:
            - x11
            - unity7
            - wayland
            - pulseaudio
            - home
            - gsettings
            - network
            - network-bind
            - cups-control
            - desktop
            - desktop-legacy
            - removable-media
            - upower-observe
            - mount-observe
        desktop: usr/share/applications/outwiker.desktop
        environment:
            LD_LIBRARY_PATH: $SNAP/usr/lib/x86_64-linux-gnu/webkit2gtk-4.0/:$SNAP/usr/lib/x86_64-linux-gnu/pulseaudio:$LD_LIBRARY_PATH

parts:
    outwiker:
        plugin: python
        python-version: python3
        source: .
        build-packages:
            - libhunspell-dev
        stage-packages:
            - libssl-dev
            - libjpeg-dev
            - libtiff-dev
            - libsdl1.2-dev
            - libnotify-dev
            - freeglut3
            - ibus-gtk3
            - zlib1g
            - libsm6
            - libpulse0
        after:
            - desktop-gtk3
            - snapcraft-preload
            - webkitgtk
        python-packages:
            - https://extras.wxpython.org/wxPython4/extras/linux/gtk3/ubuntu-16.04/wxPython-4.0.7-cp35-cp35m-linux_x86_64.whl
            - Pillow==6.1.0
            - hunspell==0.5.5
            - idna==2.8
            - pyparsing==2.4.2
        override-build: |
            snapcraftctl build
            cp -r $SNAPCRAFT_PART_SRC/usr $SNAPCRAFT_PART_INSTALL
            chmod +x $SNAPCRAFT_PART_INSTALL/usr/bin/outwiker
    snapcraft-preload:
        source: https://github.com/sergiusens/snapcraft-preload.git
        plugin: cmake
        build-packages:
          - gcc-multilib
          - g++-multilib

    webkitgtk:
        after:
            - gcc
        plugin: cmake
        configflags:
            - -DCMAKE_INSTALL_PREFIX=/
            - -DCMAKE_BUILD_TYPE=Release
            - -DPORT=GTK
            - -DENABLE_WEB_CRYPTO=0
            - -DUSE_OPENJPEG=0
            - -DUSE_WOFF2=0
            - -DUSE_GSTREAMER_GL=0
            - -DENABLE_MEDIA_SOURCE=0
            - -DCMAKE_C_COMPILER=gcc-6
            - -DCMAKE_CXX_COMPILER=g++-6
            - -DLIBEXEC_INSTALL_DIR=/usr/libexec/webkit2gtk-4.0
        source: https://www.webkitgtk.org/releases/webkitgtk-2.24.1.tar.xz
        build-packages:
            - ruby
            - libgcrypt20-dev
            - libwebp-dev
            - libxslt1-dev
            - libsecret-1-dev
            - libtasn1-6-dev
            - libenchant-dev
            - libhyphen-dev
            - libjpeg-dev
            - libsoup2.4-dev
            - libxkbcommon-dev
            - libnghttp2-14
            - libpixman-1-dev
            - libsqlite3-dev
            - libgl1-mesa-dev
            - freeglut3-dev 
            - libgirepository1.0-dev
            - libgtk-3-dev
            - libgtk2.0-dev
            - libnotify-dev
            - libgstreamer1.0-dev
            - libgstreamer-plugins-base1.0-dev
        stage-packages:
            - libc6
            - libstdc++6
            - libgl1
            - libgles2
            - geoclue-2.0
            - gperf
            - gobject-introspection

    gcc:
        plugin: nil
        override-pull: 'true'
        override-build: |
            sudo apt --yes install software-properties-common

            # Install newer GCC from Toolchain test builds PPA
            sudo add-apt-repository --yes ppa:ubuntu-toolchain-r/test
            sudo apt update
            sudo apt --yes install gcc-6 g++-6

        override-stage: 'true'
        override-prime: 'true'

