name: outwiker
version: '{version}'
summary: Cross-platform software for keeping your notes in a tree
description: |
    OutWiker is a cross-platform software for keeping your notes in a tree.
    Similar programs call "outliner", "tree-like editor" or personal wiki.
    Main difference OutWiker from other programs is a keeping notes as folders on disk.
    A notes can to have attached files. OutWiker can contain pages of different types,
    currently supports three types of pages: plain text, HTML pages and wiki pages.

grade: devel # must be 'stable' to release into candidate/stable channels
confinement: strict # use 'strict' once you have the right plugs and slots
icon: usr/share/icons/outwiker.svg
base: core18

apps:
    outwiker:
        command: desktop-launch snapcraft-preload $SNAP/usr/bin/outwiker
        plugs:
            - x11
            - unity7
            - wayland
            - pulseaudio
            - home
            - gsettings
            - network
            - network-bind
            - cups-control
            - desktop
            - desktop-legacy
            - removable-media
            - upower-observe
            - mount-observe
        desktop: usr/share/applications/outwiker.desktop
        environment:
            LD_LIBRARY_PATH: $SNAP/usr/lib/x86_64-linux-gnu/webkit2gtk-4.0/:$SNAP/usr/lib/x86_64-linux-gnu/pulseaudio:$LD_LIBRARY_PATH

parts:
    outwiker:
        plugin: python
        python-version: python3
        source: .
        build-packages:
            - libhunspell-dev
            - libwebkit2gtk-4.0-dev
            - python3-dev
            - libssl-dev
            - build-essential
            - libjpeg-dev
            - libtiff-dev
            - libsdl2-dev
            - libgstreamer-plugins-base1.0-dev
            - libnotify-dev
            - freeglut3-dev
            - libsm-dev
            - libgtk-3-dev
        stage-packages:
            - libglu1-mesa
            - libsdl2-2.0-0
            - libsndio6.1
            - libxss1
            - freeglut3
            - ibus-gtk3
            - zlib1g
            - libsm6
            - libpulse0
            - libhunspell-1.6-0
            - libwebkit2gtk-4.0-37
            - libsdl-gfx1.2-5
            - libgstreamer1.0-0
            - libslang2
        stage:
            - -usr/lib/x86_64-linux-gnu/glib-2.0/gio-querymodules
            - -usr/lib/x86_64-linux-gnu/glib-2.0/glib-compile-schemas
            - -usr/lib/x86_64-linux-gnu/libgio-2.0.so.0.5600.4
            - -usr/lib/x86_64-linux-gnu/libglib-2.0.so.0.5600.4
            - -usr/lib/x86_64-linux-gnu/libgmodule-2.0.so.0.5600.4
            - -usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0.5600.4
            - -usr/lib/x86_64-linux-gnu/libgthread-2.0.so.0.5600.4
            - -usr/lib/x86_64-linux-gnu/libibus-1.0.so.5.0.517
            - -usr/lib/x86_64-linux-gnu/libicudata.so.60.2
            - -usr/lib/x86_64-linux-gnu/libicui18n.so.60.2
            - -usr/lib/x86_64-linux-gnu/libicuio.so.60.2
            - -usr/lib/x86_64-linux-gnu/libicutest.so.60.2
            - -usr/lib/x86_64-linux-gnu/libicutu.so.60.2
            - -usr/lib/x86_64-linux-gnu/libicuuc.so.60.2
            - -usr/lib/x86_64-linux-gnu/gtk-3.0/3.0.0/immodules/im-ibus.so
            - -usr/lib/x86_64-linux-gnu/libsqlite3.so.0.8.6
            - -usr/lib/x86_64-linux-gnu/libxml2.so.2.9.4
            - -usr/lib/x86_64-linux-gnu/libcups.so.2
            - -usr/lib/x86_64-linux-gnu/libjson-glib-1.0.so.0.400.2
            - -usr/share/doc/*
        after:
            - desktop-gtk3
            - snapcraft-preload
        python-packages:
            # - https://extras.wxpython.org/wxPython4/extras/linux/gtk3/ubuntu-18.04/wxPython-4.0.7.post2-cp36-cp36m-linux_x86_64.whl
            - wxpython==4.0.7.post2
            - Pillow==7.0.0
            - cyhunspell==1.3.4
            - idna==2.9
            - pyparsing==2.4.6
        override-build: |
            snapcraftctl build
            cp -r $SNAPCRAFT_PART_SRC/usr $SNAPCRAFT_PART_INSTALL
            chmod +x $SNAPCRAFT_PART_INSTALL/usr/bin/outwiker
    snapcraft-preload:
        source: https://github.com/sergiusens/snapcraft-preload.git
        plugin: cmake
        build-packages:
          - gcc-multilib
          - g++-multilib

    desktop-gtk3:
        build-packages:
            - build-essential
            - libgtk-3-dev
        make-parameters:
            - FLAVOR=gtk3
        plugin: make
        source: https://github.com/ubuntu/snapcraft-desktop-helpers.git
        source-subdir: gtk
        stage-packages:
            - libxkbcommon0
            - ttf-ubuntu-font-family
            - dmz-cursor-theme
            - light-themes
            - adwaita-icon-theme
            - gnome-themes-standard
            - shared-mime-info
            - libgtk-3-0
            - libgdk-pixbuf2.0-0
            - libglib2.0-bin
            - libgtk-3-bin
            - unity-gtk3-module
            - libappindicator3-1
            - locales-all
            - xdg-user-dirs
            - ibus-gtk3
            - libibus-1.0-5
            - fcitx-frontend-gtk3
