#!/usr/bin/env python
# -*- coding: utf-8 -*-
# generated by wxGlade 0.6.3 on Thu Nov 18 21:58:50 2010

import wx

# begin wxGlade: extracode
# end wxGlade



class AboutDialog(wx.Dialog):
	def __init__(self, *args, **kwds):
		# begin wxGlade: AboutDialog.__init__
		kwds["style"] = wx.DEFAULT_DIALOG_STYLE|wx.RESIZE_BORDER|wx.THICK_FRAME
		wx.Dialog.__init__(self, *args, **kwds)
		self.notebook = wx.Notebook(self, -1, style=0)
		self.donatePane = wx.Panel(self.notebook, -1)
		self.aboutPane = wx.Panel(self.notebook, -1)
		self.titleLabel = wx.StaticText(self, -1, _("OutWiker"))
		self.label_1 = wx.StaticText(self, -1, _("Version:"))
		self.versionLabel = wx.StaticText(self, -1, "")
		self.label_2 = wx.StaticText(self.aboutPane, -1, _("Author: Ilin Eugeniy (aka Jenyay)"))
		self.label_3 = wx.StaticText(self.aboutPane, -1, _("License: GPL 3"))
		self.label_4 = wx.StaticText(self.aboutPane, -1, _("My site:"))
		self.siteLink = wx.HyperlinkCtrl(self.aboutPane, -1, label=_("http://jenyay.net"), url=_("http://jenyay.net"))
		self.label_5 = wx.StaticText(self.aboutPane, -1, _("OutWiker's page:"))
		self.outwikerPage = wx.HyperlinkCtrl(self.aboutPane, -1, label=_("http://jenyay.net/Soft/Outwiker"), url=_("http://jenyay.net/Soft/Outwiker"))
		self.label_6 = wx.StaticText(self.aboutPane, -1, _("Twitter:"))
		self.twitterLink = wx.HyperlinkCtrl(self.aboutPane, -1, label=_("@jenyay"), url=_("http://twitter.com/#!/jenyay"))
		self.label_7 = wx.StaticText(self.aboutPane, -1, _("E-mail:"))
		self.mailLink = wx.HyperlinkCtrl(self.aboutPane, -1, label=_("jenyay.ilin@gmail.com"), url=_("mailto:jenyay.ilin@gmail.com"))
		self.label_8 = wx.StaticText(self.donatePane, -1, _("WebMoney (WMR):"))
		self.wmrTextCtrl = wx.TextCtrl(self.donatePane, -1, _("R356551209135"), style=wx.TE_READONLY)
		self.label_10 = wx.StaticText(self.donatePane, -1, _("WebMoney (WMZ)"))
		self.wmzTextCtrl = wx.TextCtrl(self.donatePane, -1, _("Z427584680984"))
		self.label_9 = wx.StaticText(self.donatePane, -1, _("Yandex.Money"))
		self.yandexTextCtrl = wx.TextCtrl(self.donatePane, -1, _("41001580829031"), style=wx.TE_READONLY)
		self.okButton = wx.Button(self, wx.OK, _("OK"))

		self.__set_properties()
		self.__do_layout()

		self.Bind(wx.EVT_BUTTON, self.onOk, id=wx.OK)
		# end wxGlade

	def __set_properties(self):
		# begin wxGlade: AboutDialog.__set_properties
		self.SetTitle(_("About"))
		self.titleLabel.SetFont(wx.Font(15, wx.DEFAULT, wx.NORMAL, wx.NORMAL, 0, ""))
		# end wxGlade

	def __do_layout(self):
		# begin wxGlade: AboutDialog.__do_layout
		main_sizer = wx.FlexGridSizer(4, 1, 0, 0)
		grid_sizer_7 = wx.FlexGridSizer(3, 2, 0, 0)
		grid_sizer_2 = wx.FlexGridSizer(6, 1, 0, 0)
		grid_sizer_6 = wx.FlexGridSizer(1, 2, 0, 0)
		grid_sizer_5 = wx.FlexGridSizer(1, 2, 0, 0)
		grid_sizer_4 = wx.FlexGridSizer(1, 2, 0, 0)
		grid_sizer_3 = wx.FlexGridSizer(1, 2, 0, 0)
		grid_sizer_1 = wx.FlexGridSizer(1, 2, 0, 0)
		main_sizer.Add(self.titleLabel, 0, wx.ALL|wx.ALIGN_CENTER_HORIZONTAL|wx.ALIGN_CENTER_VERTICAL, 2)
		grid_sizer_1.Add(self.label_1, 0, wx.ALL|wx.ALIGN_RIGHT, 2)
		grid_sizer_1.Add(self.versionLabel, 0, wx.ALL, 2)
		grid_sizer_1.AddGrowableRow(0)
		grid_sizer_1.AddGrowableCol(0)
		grid_sizer_1.AddGrowableCol(1)
		main_sizer.Add(grid_sizer_1, 1, wx.EXPAND, 0)
		grid_sizer_2.Add(self.label_2, 0, wx.ALL, 2)
		grid_sizer_2.Add(self.label_3, 0, wx.ALL, 2)
		grid_sizer_3.Add(self.label_4, 0, wx.ALL, 2)
		grid_sizer_3.Add(self.siteLink, 1, wx.ALL|wx.EXPAND, 2)
		grid_sizer_3.AddGrowableCol(1)
		grid_sizer_2.Add(grid_sizer_3, 1, wx.EXPAND, 0)
		grid_sizer_4.Add(self.label_5, 0, wx.ALL, 2)
		grid_sizer_4.Add(self.outwikerPage, 1, wx.ALL|wx.EXPAND, 2)
		grid_sizer_4.AddGrowableCol(1)
		grid_sizer_2.Add(grid_sizer_4, 1, wx.EXPAND, 0)
		grid_sizer_5.Add(self.label_6, 0, wx.ALL, 2)
		grid_sizer_5.Add(self.twitterLink, 1, wx.ALL|wx.EXPAND, 2)
		grid_sizer_5.AddGrowableCol(1)
		grid_sizer_2.Add(grid_sizer_5, 1, wx.EXPAND, 0)
		grid_sizer_6.Add(self.label_7, 0, wx.ALL, 2)
		grid_sizer_6.Add(self.mailLink, 1, wx.ALL|wx.EXPAND, 2)
		grid_sizer_6.AddGrowableCol(1)
		grid_sizer_2.Add(grid_sizer_6, 1, wx.EXPAND, 0)
		self.aboutPane.SetSizer(grid_sizer_2)
		grid_sizer_2.AddGrowableCol(0)
		grid_sizer_7.Add(self.label_8, 0, wx.ALL|wx.ALIGN_CENTER_VERTICAL, 2)
		grid_sizer_7.Add(self.wmrTextCtrl, 0, wx.ALL|wx.EXPAND, 2)
		grid_sizer_7.Add(self.label_10, 0, wx.ALL|wx.ALIGN_CENTER_VERTICAL, 2)
		grid_sizer_7.Add(self.wmzTextCtrl, 0, wx.ALL|wx.EXPAND, 2)
		grid_sizer_7.Add(self.label_9, 0, wx.ALL|wx.ALIGN_CENTER_VERTICAL, 2)
		grid_sizer_7.Add(self.yandexTextCtrl, 0, wx.ALL|wx.EXPAND, 2)
		self.donatePane.SetSizer(grid_sizer_7)
		grid_sizer_7.AddGrowableCol(0)
		grid_sizer_7.AddGrowableCol(1)
		self.notebook.AddPage(self.aboutPane, _("About"))
		self.notebook.AddPage(self.donatePane, _("Donate"))
		main_sizer.Add(self.notebook, 1, wx.ALL|wx.EXPAND, 2)
		main_sizer.Add(self.okButton, 0, wx.ALL|wx.ALIGN_RIGHT, 2)
		self.SetSizer(main_sizer)
		main_sizer.Fit(self)
		main_sizer.AddGrowableRow(2)
		main_sizer.AddGrowableCol(0)
		self.Layout()
		self.Centre()
		# end wxGlade

	def onOk(self, event): # wxGlade: AboutDialog.<event_handler>
		self.Close()

# end of class AboutDialog


