#!/usr/bin/env python
# -*- coding: utf-8 -*-
# generated by wxGlade 0.6.3 on Mon Jan  3 16:08:33 2011

import wx
from  import 

if __name__ == "__main__":
    import gettext
    gettext.install("app") # replace with the appropriate catalog name

    app = wx.PySimpleApp(0)
    wx.InitAllImageHandlers()
    createPage = (None, -1, "")
    app.SetTopWindow(createPage)
    createPage.Show()
    app.MainLoop()
