# -*- coding: utf-8 -*-
# generated by wxGlade 0.6.3 on Sat Apr 10 19:07:28 2010

import os.path
import wx

# begin wxGlade: dependencies
# end wxGlade

# begin wxGlade: extracode

# end wxGlade

from core.application import Application
from core.factoryselector import FactorySelector
import core.commands
from core.tree import RootWikiPage
from core.search import TagsList
import core.system


class CurrentPagePanel(wx.Panel):
	def __init__(self, *args, **kwds):
		self.pageView = None

		self.imagesDir = core.system.getImagesDir()
		
		self.grayStarImage = os.path.join (self.imagesDir, "star_gray.png")
		self.goldStarImage = os.path.join (self.imagesDir, "star.png")

		# begin wxGlade: CurrentPagePanel.__init__
		kwds["style"] = wx.TAB_TRAVERSAL
		wx.Panel.__init__(self, *args, **kwds)
		self.bookmarkButton = wx.BitmapButton(self, -1, wx.Bitmap(os.path.join (self.imagesDir, "star_gray.png"), wx.BITMAP_TYPE_ANY))
		self.titleLabel = wx.StaticText(self, -1, "")
		self.tagsLabel = wx.StaticText(self, -1, _("[]"))

		self.__set_properties()
		self.__do_layout()

		self.Bind(wx.EVT_BUTTON, self.onBookmark, self.bookmarkButton)
		# end wxGlade

		Application.onWikiOpen += self.onWikiOpen
		Application.onPageSelect += self.onPageSelect
		Application.onPageRename += self.onPageRename
		Application.onPageUpdate += self.onPageUpdate
		Application.onBookmarksChanged += self.onBookmarksChanged

		self.Bind (wx.EVT_CLOSE, self.onClose)


	def Print (self):
		if Application.selectedPage != None and self.pageView != None:
			self.pageView.Print()

	
	def onClose (self, event):
		Application.onWikiOpen -= self.onWikiOpen
		Application.onPageSelect -= self.onPageSelect
		Application.onPageRename -= self.onPageRename
		Application.onPageUpdate -= self.onPageUpdate
		Application.onBookmarksChanged -= self.onBookmarksChanged

		if self.pageView != None:
			self.pageView.removeGui ()
			self.pageView.Close()
		self.Destroy()


	def onPageRename (self, page, oldsubpath):
		self.onPageUpdate (page)


	def onWikiOpen (self, root):
		self.onPageSelect (root.selectedPage if root != None else None)


	def onPageSelect (self, page):
		"""
		Событие при выборе страницы
		"""
		self.Freeze()
		self.destroyPageView()

		self.updatePageInfo (page)
		self.updatePageView (page)
		self.Thaw()


	def onPageUpdate (self, page):
		if Application.selectedPage != None and Application.selectedPage == page:
			self.updatePageInfo (page)
	

	def updateBookmarkBtn (self):
		imagePath = self.grayStarImage
		tooltip = _(u"Add to Bookmarks")

		if Application.selectedPage != None and Application.selectedPage.root.bookmarks.pageMarked (Application.selectedPage):
			imagePath = self.goldStarImage
			tooltip = _(u"Remove from Bookmarks")

		self.bookmarkButton.SetBitmapLabel (wx.Bitmap(imagePath, wx.BITMAP_TYPE_ANY))
		self.bookmarkButton.SetToolTipString (tooltip)


	def onBookmarksChanged (self, bookmarks):
		self.updateBookmarkBtn()


	def updatePageView (self, page):
		"""
		Обновить вид страницы
		"""
		if page != None:
			factory = FactorySelector.getFactory (page.getTypeString())
			self.pageView = factory.getPageView (page, self)

			assert self.pageView != None

			self.contentSizer.Add (self.pageView, 1, wx.EXPAND, 0)
			self.Layout()

			self.pageView.initGui(wx.GetApp().GetTopWindow() )


	def updatePageInfo (self, page):
		"""
		Обновить информацию о странице
		"""
		if page != None:
			title = "%s" % (page.title)
			self.titleLabel.SetLabel (title)

			if hasattr (page, "tags"):
				tags = u"[%s]" % TagsList.getTagsString (page.tags)
			else:
				tags = u"[]"

			self.tagsLabel.SetLabel (tags)

			self.updateBookmarkBtn()
		else:
			self.titleLabel.SetLabel (u"")
			self.tagsLabel.SetLabel (u"[]")

	
	def __set_properties(self):
		# begin wxGlade: CurrentPagePanel.__set_properties
		self.bookmarkButton.SetSize(self.bookmarkButton.GetBestSize())
		self.titleLabel.SetFont(wx.Font(14, wx.DEFAULT, wx.NORMAL, wx.NORMAL, 0, "MS Shell Dlg 2"))
		self.tagsLabel.SetFont(wx.Font(12, wx.MODERN, wx.ITALIC, wx.NORMAL, 0, ""))
		# end wxGlade


	def __do_layout(self):
		# begin wxGlade: CurrentPagePanel.__do_layout
		mainSizer = wx.FlexGridSizer(3, 1, 0, 0)
		contentSizer = wx.FlexGridSizer(1, 1, 0, 0)
		titleSizer = wx.FlexGridSizer(1, 3, 0, 0)
		titleSizer.Add(self.bookmarkButton, 0, 0, 0)
		titleSizer.Add(self.titleLabel, 0, wx.ALL|wx.EXPAND|wx.ALIGN_CENTER_VERTICAL, 2)
		titleSizer.Add(self.tagsLabel, 0, wx.ALL|wx.EXPAND|wx.ALIGN_CENTER_VERTICAL, 2)
		titleSizer.AddGrowableCol(1)
		mainSizer.Add(titleSizer, 1, wx.EXPAND, 0)
		contentSizer.AddGrowableRow(0)
		contentSizer.AddGrowableCol(0)
		mainSizer.Add(contentSizer, 1, wx.EXPAND, 0)
		self.SetSizer(mainSizer)
		mainSizer.Fit(self)
		mainSizer.AddGrowableRow(1)
		mainSizer.AddGrowableCol(0)
		# end wxGlade

		self.contentSizer = contentSizer


	def destroyPageView (self):
		"""
		Уничтожить текущий контрол
		"""
		if self.pageView != None:
			self.contentSizer.Detach (self.pageView)
			self.pageView.Close()
			self.pageView = None

	
	def destroyWithoutSave (self):
		"""
		Уничтожить панель без сохранения изменений.
		Нужно для перезагрузки вики
		"""
		if self.pageView != None:
			self.contentSizer.Detach (self.pageView)
			self.pageView.CloseWithoutSave()
			self.pageView = None
	

	def Save (self):
		"""
		Сохранить текущую страницу
		"""
		if self.pageView != None:
			self.pageView.Save()


	def onBookmark(self, event): # wxGlade: CurrentPagePanel.<event_handler>
		if Application.selectedPage != None:
			if not Application.selectedPage.root.bookmarks.pageMarked (Application.selectedPage):
				Application.selectedPage.root.bookmarks.add (Application.selectedPage)
			else:
				Application.selectedPage.root.bookmarks.remove (Application.selectedPage)


# end of class CurrentPagePanel


