#!/usr/bin/env python
# -*- coding: utf-8 -*-
# generated by wxGlade 0.6.3 on Fri May 21 21:23:02 2010

import wx
from MainWindow import MainWindow

if __name__ == "__main__":
    outwiker = wx.PySimpleApp(0)
    wx.InitAllImageHandlers()
    mainWnd = MainWindow(None, -1, "")
    outwiker.SetTopWindow(mainWnd)
    mainWnd.Show()
    outwiker.MainLoop()
