# -*- coding: utf-8 -*-
# generated by wxGlade 0.6.3 on Wed Oct 27 21:24:33 2010

import wx

import ConfigElements
from core.controller import Controller

# begin wxGlade: dependencies
# end wxGlade

# begin wxGlade: extracode

# end wxGlade

class EditorPanel(wx.Panel):
	def __init__(self, *args, **kwds):
		# begin wxGlade: EditorPanel.__init__
		kwds["style"] = wx.TAB_TRAVERSAL
		wx.Panel.__init__(self, *args, **kwds)
		self.fontSizeLabel = wx.StaticText(self, -1, "Font size")
		self.fontSizeSpin = wx.SpinCtrl(self, -1, "10", min=1, max=30)
		self.lineNumbersCheckBox = wx.CheckBox(self, -1, "Show line numbers")

		self.__set_properties()
		self.__do_layout()
		# end wxGlade

		self.config = wx.GetApp().config
		self.LoadState()

	def __set_properties(self):
		# begin wxGlade: EditorPanel.__set_properties
		pass
		# end wxGlade

	def __do_layout(self):
		# begin wxGlade: EditorPanel.__do_layout
		mainSizer = wx.FlexGridSizer(2, 1, 0, 0)
		grid_sizer_1 = wx.FlexGridSizer(1, 2, 0, 0)
		grid_sizer_1.Add(self.fontSizeLabel, 0, wx.ALL|wx.ALIGN_CENTER_VERTICAL, 2)
		grid_sizer_1.Add(self.fontSizeSpin, 0, wx.ALL|wx.ALIGN_RIGHT, 2)
		grid_sizer_1.AddGrowableRow(0)
		grid_sizer_1.AddGrowableCol(0)
		grid_sizer_1.AddGrowableCol(1)
		mainSizer.Add(grid_sizer_1, 1, wx.EXPAND, 0)
		mainSizer.Add(self.lineNumbersCheckBox, 0, wx.ALL|wx.ALIGN_CENTER_VERTICAL, 2)
		self.SetSizer(mainSizer)
		mainSizer.Fit(self)
		mainSizer.AddGrowableCol(0)
		# end wxGlade


	def LoadState(self):
		# Размер шрифта
		self.fontSize = ConfigElements.IntegerElement (u"Font", u"size",
				self.config, self.fontSizeSpin, 10, 1, 30)

		# Показывать ли номера строк?
		self.lineNumbers = ConfigElements.BooleanElement (u"General", u"ShowLineNumbers",
				self.config, self.lineNumbersCheckBox, False)
	

	def Save (self):
		generateEvent = self.fontSize.isValueChanged() or self.lineNumbers.isValueChanged()

		self.fontSize.save()
		self.lineNumbers.save()

		if generateEvent:
			Controller.instance().onEditorConfigChange()


# end of class EditorPanel


