# -*- coding: utf-8 -*-
# generated by wxGlade 0.6.3 on Wed Oct 27 21:24:33 2010

import wx

import ConfigElements
from core.controller import Controller
from core.application import Application

# begin wxGlade: dependencies
# end wxGlade

# begin wxGlade: extracode

# end wxGlade

class EditorPanel(wx.Panel):
	def __init__(self, *args, **kwds):
		# begin wxGlade: EditorPanel.__init__
		kwds["style"] = wx.TAB_TRAVERSAL
		wx.Panel.__init__(self, *args, **kwds)
		self.fontLabel = wx.StaticText(self, -1, _("Font"))
		self.fontPicker = wx.FontPickerCtrl(self, -1)
		self.lineNumbersCheckBox = wx.CheckBox(self, -1, _("Show line numbers"))

		self.__set_properties()
		self.__do_layout()
		# end wxGlade

		self.LoadState()

	def __set_properties(self):
		# begin wxGlade: EditorPanel.__set_properties
		pass
		# end wxGlade

	def __do_layout(self):
		# begin wxGlade: EditorPanel.__do_layout
		mainSizer = wx.FlexGridSizer(2, 1, 0, 0)
		grid_sizer_3 = wx.FlexGridSizer(1, 2, 0, 0)
		grid_sizer_3.Add(self.fontLabel, 0, wx.ALL|wx.ALIGN_CENTER_VERTICAL, 2)
		grid_sizer_3.Add(self.fontPicker, 1, wx.ALL|wx.EXPAND|wx.ALIGN_CENTER_VERTICAL, 2)
		grid_sizer_3.AddGrowableRow(0)
		grid_sizer_3.AddGrowableCol(1)
		mainSizer.Add(grid_sizer_3, 1, wx.EXPAND, 0)
		mainSizer.Add(self.lineNumbersCheckBox, 0, wx.ALL|wx.ALIGN_CENTER_VERTICAL, 2)
		self.SetSizer(mainSizer)
		mainSizer.Fit(self)
		mainSizer.AddGrowableCol(0)
		# end wxGlade


	def LoadState(self):
		# Показывать ли номера строк?
		self.lineNumbers = ConfigElements.BooleanElement (Application.config.lineNumbersOption, self.lineNumbersCheckBox)

		# Шрифт для редактора
		self.fontEditor = ConfigElements.FontElement (Application.config.fontEditorOption, self.fontPicker)
	

	def Save (self):
		self.lineNumbers.save()
		self.fontEditor.save()

		Controller.instance().onEditorConfigChange()


# end of class EditorPanel


