# -*- coding: utf-8 -*-
# generated by wxGlade 0.6.3 on Sat Oct 23 11:59:26 2010

import wx

# begin wxGlade: dependencies
# end wxGlade

# begin wxGlade: extracode

# end wxGlade

class GeneralPanel(wx.ScrolledWindow):
	def __init__(self, *args, **kwds):
		self.config = wx.GetApp().config

		# begin wxGlade: GeneralPanel.__init__
		kwds["style"] = wx.TAB_TRAVERSAL
		wx.ScrolledWindow.__init__(self, *args, **kwds)
		self.minimizeCheckBox = wx.CheckBox(self, -1, "Minimize to tray")
		self.startIconizedCheckBox = wx.CheckBox(self, -1, "Start with main window iconized")
		self.askBeforeExitCheckBox = wx.CheckBox(self, -1, "Ask before exit")
		self.static_line_2 = wx.StaticLine(self, -1)
		self.history_label = wx.StaticText(self, -1, "Recent files history length (apply after restart)")
		self.historySpin = wx.SpinCtrl(self, -1, "5", min=0, max=20, style=wx.SP_ARROW_KEYS|wx.TE_PROCESS_ENTER|wx.TE_PROCESS_TAB|wx.TE_AUTO_URL)
		self.autoopenCheckBox = wx.CheckBox(self, -1, "Automatically open the recent file")
		self.titleFormatLabel = wx.StaticText(self, -1, "Main window title format")
		self.titleFormatText = wx.TextCtrl(self, -1, "")
		self.macrosLabel = wx.StaticText(self, -1, "Macros for title:\n{file} - open wiki file name\n{page} - open page title")
		self.static_line_3 = wx.StaticLine(self, -1)
		self.static_line_1 = wx.StaticLine(self, -1)

		self.__set_properties()
		self.__do_layout()
		# end wxGlade

		self.LoadState()


	def __set_properties(self):
		# begin wxGlade: GeneralPanel.__set_properties
		self.SetSize((508, 408))
		self.SetFocus()
		self.SetScrollRate(0, 0)
		self.askBeforeExitCheckBox.SetValue(1)
		# end wxGlade


	def __do_layout(self):
		# begin wxGlade: GeneralPanel.__do_layout
		main_sizer = wx.FlexGridSizer(9, 1, 0, 0)
		grid_sizer_2 = wx.FlexGridSizer(1, 2, 0, 0)
		history_size = wx.FlexGridSizer(1, 2, 0, 0)
		main_sizer.Add(self.minimizeCheckBox, 0, wx.ALL|wx.ALIGN_CENTER_VERTICAL, 2)
		main_sizer.Add(self.startIconizedCheckBox, 0, wx.ALL, 2)
		main_sizer.Add(self.askBeforeExitCheckBox, 0, wx.ALL|wx.ALIGN_CENTER_VERTICAL, 2)
		main_sizer.Add(self.static_line_2, 0, wx.EXPAND, 0)
		history_size.Add(self.history_label, 0, wx.ALL|wx.ALIGN_CENTER_VERTICAL, 2)
		history_size.Add(self.historySpin, 0, wx.ALL|wx.ALIGN_RIGHT, 2)
		history_size.AddGrowableRow(0)
		history_size.AddGrowableCol(0)
		history_size.AddGrowableCol(1)
		main_sizer.Add(history_size, 1, wx.EXPAND, 0)
		main_sizer.Add(self.autoopenCheckBox, 0, wx.ALL|wx.ALIGN_CENTER_VERTICAL, 2)
		grid_sizer_2.Add(self.titleFormatLabel, 0, wx.ALL|wx.ALIGN_CENTER_VERTICAL, 2)
		grid_sizer_2.Add(self.titleFormatText, 0, wx.ALL|wx.EXPAND, 2)
		grid_sizer_2.AddGrowableCol(1)
		main_sizer.Add(grid_sizer_2, 1, wx.EXPAND, 0)
		main_sizer.Add(self.macrosLabel, 0, wx.ALL, 2)
		main_sizer.Add(self.static_line_3, 0, wx.EXPAND, 0)
		main_sizer.Add(self.static_line_1, 0, wx.EXPAND, 0)
		self.SetSizer(main_sizer)
		main_sizer.AddGrowableCol(0)
		# end wxGlade
	

	def LoadState (self):
		"""
		Загрузить состояние страницы из конфига
		"""
		self.__loadGeneralOptions()
		self.__loadRecentOptions()

	
	def __loadRecentOptions (self):
		"""
		Опции, связанные с последними открытыми файлами
		"""
		# Длина истории последних открытых файлов
		try:
			self.historySpin.SetValue (self.config.getint (u"RecentWiki", u"maxcount"))
		except:
			pass

		# Открывать последнюю вики при запуске?
		try:
			self.autoopenCheckBox.SetValue (self.config.getbool (u"RecentWiki", u"AutoOpen"))
		except:
			pass

		# Формат заголовка страницы
		try:
			self.titleFormatText.SetValue (self.config.get (u"MainWindow", u"Title"))
		except:
			self.titleFormatText.SetValue (u"")
	

	def __loadGeneralOptions (self):
		"""
		Опции для сворачивания окна в трей
		"""
		# Сворачивать в трей?
		try:
			self.minimizeCheckBox.SetValue (self.config.getbool (u"General", u"MinimizeToTray"))
		except:
			pass

		# Запускаться свернутым?
		try:
			self.startIconizedCheckBox.SetValue (self.config.getbool (u"General", u"StartIconized"))
		except:
			pass

		# Задавать вопрос перед выходом из программы?
		try:
			self.askBeforeExitCheckBox.SetValue (self.config.getbool (u"General", u"AskBeforeExit"))
		except:
			pass


	def Save(self):
		"""
		Сохранить состояние страницы в конфиг
		"""
		self.config.set (u"General", u"StartIconized", self.startIconizedCheckBox.IsChecked() )
		self.config.set (u"General", u"MinimizeToTray", self.minimizeCheckBox.IsChecked() )
		self.config.set (u"General", u"AskBeforeExit", self.askBeforeExitCheckBox.IsChecked() )

		self.config.set (u"RecentWiki", u"maxcount", self.historySpin.GetValue () )
		self.config.set (u"RecentWiki", u"AutoOpen", self.autoopenCheckBox.IsChecked() )

		self.config.set (u"MainWindow", u"Title", self.titleFormatText.GetValue ())

# end of class GeneralPanel


