# -*- coding: utf-8 -*-
# generated by wxGlade 0.6.3 on Tue May 31 20:54:02 2011

import wx

import ConfigElements
from core.application import Application
from gui.guiconfig import HtmlRenderConfig
from core.config import FontOption

# begin wxGlade: dependencies
# end wxGlade

# begin wxGlade: extracode

# end wxGlade

class HtmlRenderPanel(wx.Panel):
	def __init__(self, *args, **kwds):
		# begin wxGlade: HtmlRenderPanel.__init__
		kwds["style"] = wx.TAB_TRAVERSAL
		wx.Panel.__init__(self, *args, **kwds)
		self.fontLabel = wx.StaticText(self, -1, _("Font"))
		self.fontPicker = wx.FontPickerCtrl(self, -1)

		self.__set_properties()
		self.__do_layout()
		# end wxGlade

		self.config = HtmlRenderConfig (Application.config)

		self.LoadState()


	def __set_properties(self):
		# begin wxGlade: HtmlRenderPanel.__set_properties
		self.SetSize((309, 199))
		# end wxGlade


	def __do_layout(self):
		# begin wxGlade: HtmlRenderPanel.__do_layout
		mainSizer = wx.FlexGridSizer(1, 1, 0, 0)
		grid_sizer_5 = wx.FlexGridSizer(1, 2, 0, 0)
		grid_sizer_5.Add(self.fontLabel, 0, wx.ALL|wx.ALIGN_CENTER_VERTICAL, 2)
		grid_sizer_5.Add(self.fontPicker, 1, wx.EXPAND, 0)
		grid_sizer_5.AddGrowableCol(1)
		mainSizer.Add(grid_sizer_5, 1, wx.EXPAND, 0)
		self.SetSizer(mainSizer)
		mainSizer.AddGrowableCol(0)
		# end wxGlade


	def LoadState(self):
		# Шрифт для HTML-рендера
		fontOption = FontOption (self.config.fontFaceNameOption, 
				self.config.fontSizeOption, 
				self.config.fontIsBold, 
				self.config.fontIsItalic)

		self.fontEditor = ConfigElements.FontElement (fontOption, self.fontPicker)


	def Save (self):
		self.fontEditor.save()

		#Application.onEditorConfigChange()

# end of class HtmlRenderPanel


