#!/usr/bin/env python
# -*- coding: utf-8 -*-
# generated by wxGlade 0.6.3 on Sat Oct 23 11:20:17 2010

import wx
from PrefDialog import PrefDialog

if __name__ == "__main__":
    app = wx.PySimpleApp(0)
    wx.InitAllImageHandlers()
    prefDialog = PrefDialog(None, -1, "")
    app.SetTopWindow(prefDialog)
    prefDialog.Show()
    app.MainLoop()
