#!/usr/bin/env python
# -*- coding: utf-8 -*-
# generated by wxGlade 0.6.3 on Thu Nov 18 21:58:50 2010

import wx

# begin wxGlade: extracode
# end wxGlade



class AboutDialog(wx.Dialog):
    def __init__(self, currversion, *args, **kwds):
        # begin wxGlade: AboutDialog.__init__
        kwds["style"] = wx.DEFAULT_DIALOG_STYLE|wx.RESIZE_BORDER|wx.THICK_FRAME
        wx.Dialog.__init__(self, *args, **kwds)
        self.notebook = wx.Notebook(self, -1, style=0)
        self.thanksPane = wx.Panel(self.notebook, -1)
        self.aboutPane = wx.Panel(self.notebook, -1)
        self.titleLabel = wx.StaticText(self, -1, _("OutWiker"))
        self.versionTitleLabel = wx.StaticText(self, -1, _("Version:"))
        self.versionLabel = wx.StaticText(self, -1, "")
        self.authonLabel = wx.StaticText(self.aboutPane, -1, _("Author: Ilin Eugeniy (aka Jenyay)"))
        self.licenseLabel = wx.StaticText(self.aboutPane, -1, _("License: GPL 3"))
        self.siteLabel = wx.StaticText(self.aboutPane, -1, _("My site:"))
        self.siteLink = wx.HyperlinkCtrl(self.aboutPane, -1, label=_("http://jenyay.net"), url=_("http://jenyay.net"))
        self.pageLabel = wx.StaticText(self.aboutPane, -1, _("OutWiker's page:"))
        self.outwikerPage = wx.HyperlinkCtrl(self.aboutPane, -1, label=_("http://jenyay.net/Soft/Outwiker"), url=_("http://jenyay.net/Soft/Outwiker"))
        self.twitterLabel = wx.StaticText(self.aboutPane, -1, _("Twitter:"))
        self.twitterLink = wx.HyperlinkCtrl(self.aboutPane, -1, label=_("@jenyay"), url=_("http://twitter.com/#!/jenyay"))
        self.mailLabel = wx.StaticText(self.aboutPane, -1, _("E-mail:"))
        self.mailLink = wx.HyperlinkCtrl(self.aboutPane, -1, label=_("jenyay.ilin@gmail.com"), url=_("mailto:jenyay.ilin@gmail.com"))
        self.thanksTextCtrl = wx.TextCtrl(self.thanksPane, -1, _("The program uses some sets of free icons taken from sites famfamfam.com and yusukekamiyamane.com. Many thanks to the authors of those sites.\n\n\nThanks Nabrodov Alexey (http://averr.in/) for the program icon. \n\nThanks Cheshkov Iliya (http://ilyuxaif.livejournal.com) for english help correction. \n\nThanks Yury aka Cuprum (http://cuprum.name/) for the icons of browsers and operating systems and \"dark\" style. \n\nThanks linda_kaioh (http://linda-kaioh.livejournal.com/) for the program testing and \"green\" style. \n\nThanks Vitaliy Yakovchuk for the ukrainian translation.\n\nRendering the formulas uses mimeTeX."), style=wx.TE_MULTILINE|wx.TE_READONLY)
        self.okButton = wx.Button(self, wx.ID_OK, "")

        self.__set_properties()
        self.__do_layout()
        # end wxGlade

        self.currversion = currversion
        self.versionLabel.SetLabel (str (self.currversion))


    def __set_properties(self):
        # begin wxGlade: AboutDialog.__set_properties
        self.SetTitle(_("About"))
        self.SetSize((450, 350))
        self.titleLabel.SetFont(wx.Font(15, wx.DEFAULT, wx.NORMAL, wx.NORMAL, 0, ""))
        self.okButton.SetFocus()
        self.okButton.SetDefault()
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: AboutDialog.__do_layout
        main_sizer = wx.FlexGridSizer(4, 1, 0, 0)
        thanksSizer = wx.FlexGridSizer(1, 1, 0, 0)
        grid_sizer_2 = wx.FlexGridSizer(6, 1, 0, 0)
        mailSizer = wx.FlexGridSizer(1, 2, 0, 0)
        twitterSizer = wx.FlexGridSizer(1, 2, 0, 0)
        pageSizer = wx.FlexGridSizer(1, 2, 0, 0)
        siteSizer = wx.FlexGridSizer(1, 2, 0, 0)
        grid_sizer_1 = wx.FlexGridSizer(1, 2, 0, 0)
        main_sizer.Add(self.titleLabel, 0, wx.ALL|wx.ALIGN_CENTER_HORIZONTAL|wx.ALIGN_CENTER_VERTICAL, 2)
        grid_sizer_1.Add(self.versionTitleLabel, 0, wx.ALL|wx.ALIGN_RIGHT, 2)
        grid_sizer_1.Add(self.versionLabel, 0, wx.ALL, 2)
        grid_sizer_1.AddGrowableRow(0)
        grid_sizer_1.AddGrowableCol(0)
        grid_sizer_1.AddGrowableCol(1)
        main_sizer.Add(grid_sizer_1, 1, wx.EXPAND, 0)
        grid_sizer_2.Add(self.authonLabel, 0, wx.ALL, 2)
        grid_sizer_2.Add(self.licenseLabel, 0, wx.ALL, 2)
        siteSizer.Add(self.siteLabel, 0, wx.ALL, 2)
        siteSizer.Add(self.siteLink, 1, wx.ALL|wx.ALIGN_RIGHT, 2)
        siteSizer.AddGrowableCol(1)
        grid_sizer_2.Add(siteSizer, 1, wx.EXPAND, 0)
        pageSizer.Add(self.pageLabel, 0, wx.ALL, 2)
        pageSizer.Add(self.outwikerPage, 1, wx.ALL|wx.ALIGN_RIGHT, 2)
        pageSizer.AddGrowableCol(1)
        grid_sizer_2.Add(pageSizer, 1, wx.EXPAND, 0)
        twitterSizer.Add(self.twitterLabel, 0, wx.ALL, 2)
        twitterSizer.Add(self.twitterLink, 1, wx.ALL|wx.ALIGN_RIGHT, 2)
        twitterSizer.AddGrowableCol(1)
        grid_sizer_2.Add(twitterSizer, 1, wx.EXPAND, 0)
        mailSizer.Add(self.mailLabel, 0, wx.ALL, 2)
        mailSizer.Add(self.mailLink, 1, wx.ALL|wx.ALIGN_RIGHT, 2)
        mailSizer.AddGrowableCol(1)
        grid_sizer_2.Add(mailSizer, 1, wx.EXPAND, 0)
        self.aboutPane.SetSizer(grid_sizer_2)
        grid_sizer_2.AddGrowableCol(0)
        thanksSizer.Add(self.thanksTextCtrl, 0, wx.ALL|wx.EXPAND, 2)
        self.thanksPane.SetSizer(thanksSizer)
        thanksSizer.AddGrowableRow(0)
        thanksSizer.AddGrowableCol(0)
        self.notebook.AddPage(self.aboutPane, _("About"))
        self.notebook.AddPage(self.thanksPane, _("Thanks"))
        main_sizer.Add(self.notebook, 1, wx.ALL|wx.EXPAND, 2)
        main_sizer.Add(self.okButton, 0, wx.ALL|wx.ALIGN_RIGHT|wx.ALIGN_CENTER_VERTICAL, 4)
        self.SetSizer(main_sizer)
        main_sizer.AddGrowableRow(2)
        main_sizer.AddGrowableCol(0)
        self.Layout()
        self.Centre()
        # end wxGlade

# end of class AboutDialog


