# -*- coding: utf-8 -*-

ID_MOUSE_LEFT = 1
ID_MOUSE_MIDDLE = 2
ID_MOUSE_RIGHT = 3

ID_KEY_SHIFT = 1
ID_KEY_CTRL = 4

MENU_FILE = 'Menu_File'
MENU_EDIT = 'Menu_Edit'
MENU_TREE = 'Menu_Tree'
MENU_TOOLS = 'Menu_Tools'
MENU_BOOKMARKS = 'Menu_Bookmarks'
MENU_VIEW = 'Menu_View'
MENU_VIEW_GOTO = 'Menu_View_Goto'
MENU_HELP = 'Menu_Help'
MENU_TOOLBARS = 'Menu_Toolbars'

TOOLBAR_GENERAL = 'General'
TOOLBAR_PLUGINS = 'Plugins'

# Period for check changes in the attach folder (in ms)
ATTACH_CHECK_PERIOD = 300

TOOLBAR_ORDER_GENERAL = 0
TOOLBAR_ORDER_TEXT = 100
TOOLBAR_ORDER_PLUGIN = 200
TOOLBAR_ORDER_PLUGINS_OTHER = 300

RECENT_COLORS_COUNT = 16
