#!/bin/sh

echo "pyversions=2.6,2.7\n" > /usr/share/python-support/outwiker.private
find /usr/share/outwiker/ -type f -name "*.py" >> /usr/share/python-support/outwiker.private
# update-python-modules outwiker.private

if which update-python-modules >/dev/null 2>&1; then
	update-python-modules  outwiker.private
fi

set -e
if [ "$1" = "configure" ] && [ -x "`which update-menus 2>/dev/null`" ] ; then
	update-menus
fi
