#!/bin/sh

echo "pyversions=2.6,2.7\n" > /usr/share/python-support/outwiker.public
find /usr/share/pyshared/outwiker/ -type f >> /usr/share/python-support/outwiker.public
update-python-modules outwiker.public

set -e
if [ "$1" = "configure" ] && [ -x "`which update-menus 2>/dev/null`" ] ; then
	update-menus
fi
