# .github/workflows/build-windows.yml
name: OutWiker Build (Windows)

on: [push, workflow_dispatch]

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

      - name: Download and install Python 3.8 32-bit
        run: |
          Invoke-WebRequest -Uri "https://www.python.org/ftp/python/3.8.10/python-3.8.10.exe" -OutFile "python-installer.exe"
          Start-Process .\python-installer.exe -ArgumentList "/quiet InstallAllUsers=1 PrependPath=0 TargetDir=C:\Python38" -Wait
          echo "C:\Python38" >> $env:GITHUB_PATH
          echo "pythonLocation=C:\Python38" >> $env:GITHUB_ENV

      - name: Check Python version
        run: C:\Python38\python.exe --version

      #- name: Set up Python 3.8
      #  uses: actions/setup-python@v5
      #  with:
      #    python-version: '3.8'

      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~\AppData\Local\pip\Cache
          key: windows-pip-${{ hashFiles('**/pyproject.toml') }}
          restore-keys: |
            windows-pip-

      - name: Cache uv environments
        uses: actions/cache@v4
        with:
          path: |
            ~\AppData\Local\uv
            .venv
          key: windows-uv-${{ hashFiles('**/pyproject.toml') }}
          restore-keys: |
            windows-uv-

      - name: Install uv
        uses: astral-sh/setup-uv@v6

      - name: Sync dependencies
        run: uv sync --python "C:\Python38\python.exe" --dev

      - name: Get OutWiker version
        shell: bash
        run: |
          OUTWIKER_VERSION=$(uv run python -c "import outwiker; print(outwiker.__version_str__)")
          echo "OUTWIKER_VERSION=$OUTWIKER_VERSION" >> $GITHUB_ENV

      - name: Check OutWiker version
        shell: bash
        run: |
          echo "OutWiker version: ${{ env.OUTWIKER_VERSION }}"

      - name: Build OutWiker (Windows)
        run: uv run inv win

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: outwiker_unstable_windows_${{ env.OUTWIKER_VERSION }}
          path: build/${{ env.OUTWIKER_VERSION }}/windows/*.zip
          path: build/${{ env.OUTWIKER_VERSION }}/windows/*.7z
          path: build/${{ env.OUTWIKER_VERSION }}/windows/*.exe
          path: build/${{ env.OUTWIKER_VERSION }}/windows/outwiker_exe/

